#!/bin/bash
# +---------------------+
# |       _ _       _	|
# |  _ __| | | _ __/ |	|
# | | '_ \_  _| '_ \ |	|
# | | .__/ |_|| .__/_|	|
# | |_|       |_|	|
# +---------------------+
# this file is to compile the executables
# and cleanup all of the files
# and create the cfg files but they are not required
# note that the cfg files need to be in the same path than the
# executable. this can be changed in the source file.
# to compile all of the programs run this command:
# 		sudo ./comp 9


WEBPATH=/var/www/html/exe/
MAKENAMEW32C=p4p1-o_32_Vx.exe
MAKENAMEW64C=p4p1-o_64_Vx.exe
MAKENAMELC=p4p1-o_Vx
MAKENAMELS=p4p1-s_Vx
me=`whoami`
err=`$?`

if [[ "$UID" -ne "$ROOT_UID" ]]; then

	echo "Must be root to run this script."
	exit $E_NOTROOT


elif [ "$1" = "mrproper" ]; then

        echo "*       _ _       _"
        echo "*  _ __| | | _ __/ |"
        echo "* | '_ \\_  _| '_\\  |"
        echo "* | .__/ |_|| .__/_|"
        echo "* |_|       |_|"
        echo "*****mrproper********"
        echo "[*] Copy windows client and server to version"
        cp -v *.exe version/
	echo "[*] Copy linux server to version"
	cp -v p4p1-s_server version/
	echo "[*] Copy linux client to version"
	cp -v p4p1-o_V* version/
        echo "[*] Remove exe"
        rm -rf *.exe

        echo "[*] Remove server executable"
	rm -rf p4p1-s_linux

else

	if [ "$1" = "-h" ]; then

		echo "usage:"
		echo "./comp -c                   -> config mode"
		echo "./comp [version number]     -> basic setup"
		echo "./comp mrproper             -> clean up files"

	elif [ "$1" = "-c" ]; then

		echo "*       _ _       _"
		echo "*  _ __| | | _ __/ |"
		echo "* | '_ \\_  _| '_\\  |"
		echo "* | .__/ |_|| .__/_|"
		echo "* |_|       |_|"
		echo "******Configure******"
		echo "[&] Configuring client"
		echo "[*] Enter custom port"
		read portno
		echo "[*] Enter custom path for download"
		read path
		echo "[!] The path function is not stable it might not work."

		echo $portno > port.cfg
		echo $path > path.cfg


	else

		echo "*       _ _       _"
		echo "*  _ __| | | _ __/ |"
		echo "* | '_ \\_  _| '_\\  |"
		echo "* | .__/ |_|| .__/_|"
		echo "* |_|       |_|"
		echo "*********************"

		if [ -z "$1" ]; then

			echo "[!] Error: Not enought arguments"
			exit -1

		else

			VERSION=$1

			echo "[*] Making p4p1 version $VERSION"
			make
			if [ "$err" = "2" ]; then
				echo "[!] Please download mingw"
				echo "[*] The program will compile the linux client and server"
				echo "[*] Press enter to continue"
				read
				make linux
			fi

			echo "[*] Renaming files"
			if [ "$err" = "2" ]; then
				echo "[*] only renaming linux version"
				mv -v $MAKENAMELC p4p1-o_V$VERSION
				mv -v $MAKENAMELS p4p1-s_V$VERSION
			else
				mv -v $MAKENAMEW32 p4p1-o_32_V$VERSION.exe
				mv -v $MAKENAMEW64 p4p1-o_64_V$VERSION.exe
				mv -v $MAKENAMELC p4p1-o_V$VERSION
				mv -v $MAKENAMELS p4p1-s_V$VERSION
			fi

			if [ $me  = "fu" ]; then
				echo "[*] Copying to website"
				cp p4p1-o_32_V$VERSION.exe $WEBPATH
				cp p4p1-o_64_V$VERSION.exe $WEBPATH
				cp p4p1-o_V$VERSION $WEBPATH
				cp p4p1-s_V$VERSION $WEBPATH
			fi

			echo "[*] Setting up nc for listening on default p4p1 port"
			SERVEREXECL=p4p1-s_V$VERSION
			./$SERVEREXECL

		fi

	fi

fi

exit
